### ISSUE TITLE
Crash: Message Too Long

### ISSUE THREAD

**Issue by jojolepro** [randomPoison/amethyst-editor#25]
Already an issue on amethyst-editor-sync, but recreating here

issue thread '<unnamed>' panicked at 'Failed to send message: Os { code: 90, kind: Other, message: "Message too long" }', libcore/result.rs:1009:5

**Comment by randomPoison** [comment]
Ah, no need to open an issue here since it's a duplicate of randomPoison/amethyst-editor-sync#12. Sorry, should have been more clear about that!
