### ISSUE TITLE
Edit component values

### ISSUE THREAD

**Issue by randomPoison** [randomPoison/amethyst-editor#36]
> This requires https://github.com/randomPoison/amethyst-editor-sync/issues/27 to be implemented.

With support for editing resources added in #34, we can add support for editing component in the same manner. The `data-display` component is already being used to show component data, so all we need to do is listen to the `submit` event and send the edited data to the game the same way that we're currently doing for resources.

I'm happy to answer any questions or provide mentorship for anyone who wants to take on this task 🙂

**Comment by Hourann** [comment]
I have spent some time to understand the framework of this repo and amethyst-editor-sync. Can I try it?

**Comment by randomPoison** [comment]
I've already started this work on the amethyst-editor-sync side, and it would make more sense for me to also implement the functionality in the editor, sorry 😓

I'm glad that you're interested in helping out though 😁 If there's another task you'd like to work on, please feel free to do so!

**Comment by Hourann** [comment]
Ok. I didn’t realize there are an active branch working on this until I was ready to submit on amethyst-editor-sync side😅. I'm a beginner to amethyst and have learned a lot from amethyst-editor-sync. Thank you for your awesome work.
